language: en-US
enable_free_tier: true
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""
  review_status: false
  commit_status: false
  changed_files_summary: false
  sequence_diagrams: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  poem: false
  labeling_instructions:
    - label: ""
      instructions: ""
  path_filters: []
  path_instructions:
    - path: ""
      instructions: ""
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  tools:
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    gitleaks:
      enabled: false
chat:
  auto_reply: true